// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scratch;

namespace Scratch.Migrations
{
    [DbContext(typeof(ScratchContext))]
    [Migration("20210511174657_Sixth")]
    partial class Sixth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Scratch.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("OtherPersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OtherPersonId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Scratch.Person", b =>
                {
                    b.HasOne("Scratch.Person", "OtherPerson")
                        .WithMany("Friends")
                        .HasForeignKey("OtherPersonId");

                    b.Navigation("OtherPerson");
                });

            modelBuilder.Entity("Scratch.Person", b =>
                {
                    b.Navigation("Friends");
                });
#pragma warning restore 612, 618
        }
    }
}
